[package]
name = "datamodel-renderer"
version = "0.1.0"
edition = "2021"

[dependencies]
once_cell = "1.20.2"
psl.workspace = true
regex = "1"
base64 = "0.22.1"

[dev-dependencies]
expect-test = "1.5.0"
indoc.workspace = true
