[package]
name = "parser-database"
version = "0.1.0"
edition = "2021"

[dependencies]
diagnostics = { path = "../diagnostics" }
schema-ast = { path = "../schema-ast" }

either = "1.13.0"
enumflags2 = "0.7"
indexmap = "2.6.0"
rustc-hash = "2.0.0"
