[package]
name = "schema-connector"
version = "0.1.0"
edition = "2021"

[dependencies]
psl.workspace = true
quaint = { workspace = true, optional = true }
serde.workspace = true
serde_json.workspace = true
user-facing-errors = { path = "../../../libs/user-facing-errors" }

chrono = "0.4"
enumflags2 = "0.7"
sha2 = "0.10.8"
tracing = "0.1"
tracing-error = "0.2"

[features]
mssql = ["user-facing-errors/mssql", "quaint"]
mysql = ["user-facing-errors/mysql", "quaint"]
postgresql = ["user-facing-errors/postgresql", "quaint"]
sqlite = ["user-facing-errors/sqlite", "quaint"]
