[package]
edition = "2021"
name = "query-core"
version = "0.1.0"

[dependencies]
async-trait = "0.1"
bigdecimal = "0.4"
chrono = "0.4"
connection-string.workspace = true 
connector = { path = "../connectors/query-connector", package = "query-connector" }
crossbeam-channel = "0.5.13"
psl.workspace = true
futures = "0.3"
indexmap = { version = "2.6", features = ["serde"] }
itertools = "0.13"
once_cell = "1"
petgraph = "0.6"
prisma-models = { path = "../prisma-models", features = ["default_generators"] }
opentelemetry = { version = "0.17.0", features = ["rt-tokio", "serialize"] }
query-engine-metrics = {path = "../metrics"}
serde.workspace = true
serde_json.workspace = true
thiserror = "1.0"
tokio.workspace = true
tracing = { version = "0.1", features = ["attributes"] }
tracing-futures = "0.2"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-opentelemetry = "0.17.4"
user-facing-errors = { path = "../../libs/user-facing-errors" }
uuid = "1"
cuid = "1.3"
schema = { path = "../schema" }
lru = "0.12.5"
enumflags2 = "0.7"

