[package]
name = "schema"
version = "0.1.0"
edition = "2021"

[dependencies]
prisma-models = { path = "../prisma-models" }
psl.workspace = true
rustc-hash = "2.0.0"
once_cell = "1"

[dev-dependencies]
codspeed-criterion-compat = "2.7.2"

[[bench]]
name = "schema_builder_bench"
harness = false
